# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11bcdb16b00cf8be7138ceef13aaea9848bc3515a26a5e9aefa1d6c228a784b3ed1d7b270f2c6fe3f2789ee0bed5bb87bbc3aa3a2122ce4b9aa7b047cc626b78

test:
  secret_key_base: e1e60a27aea36870f2efbc100691a5c6a80ade6edab9a7462ee61d86e868d766513db802edce76656fc187c409897e0c33b3d63bf281bade8375e97ea349b9e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
